name: custom

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx tsc
      - name: Test custom summary hbs file
        run: node dist/index.js custom ctrf-reports/ctrf-report.json templates/custom-summary.hbs
        if: github.event_name != 'schedule'
      - name: Test custom summary string
        run: node dist/index.js custom ctrf-reports/ctrf-report.json "I'm a custom summary string!"
        if: github.event_name != 'schedule'
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ctrf-reports/ctrf-report.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: custom-artifact-name
          path: ctrf-reports/ctrf-report-no-fails.json
