name: failed

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx tsc
      - name: Test failed with title
        run: node dist/index.js failed ctrf-reports/ctrf-report.json --title "Failed With Title"
      - name: Test failed no title
        run: node dist/index.js failed ctrf-reports/ctrf-report.json
      - name: Test failed folded
        run: node dist/index.js failed-folded ctrf-reports/ctrf-report.json --title "Failed Folded"
      - name: Test failed rate
        run: node dist/index.js failed-rate ctrf-reports/ctrf-report.json --title "Failed Rate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ctrf-reports/ctrf-report.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: custom-artifact-name
          path: ctrf-reports/ctrf-report-no-fails.json
