name: skipped

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx tsc
      - name: Test skipped with title
        run: node dist/index.js skipped ctrf-reports/ctrf-report.json --title "Skipped With Title"
      - name: Test failed no title
        run: node dist/index.js skipped ctrf-reports/ctrf-report.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ctrf-reports/ctrf-report.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: custom-artifact-name
          path: ctrf-reports/ctrf-report-no-fails.json
