name: build-and-test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run all:action
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1.0.19
        with:
          report-path: './ctrf/*.json'
          integrations-config: |
            {
              "slack": {
                "enabled": true,
                "action": "results",
                "options": {
                  "title": "Test Results",
                  "prefix": "Custom prefix",
                  "suffix": "Custom suffix",
                  "consolidated": false,
                  "onFailOnly": false
                }
              }
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
              