name: flaky

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx tsc
      - name: Generate Markdown Summary
        uses: Ma11hewThomas/github-markdown-builder@v1
        with:
          template-file-path: 'templates/custom-summary.hbs'
          json-file-path: 'ctrf-reports/ctrf-report.json' # Optional
          summary: true # Set to true to post to GitHub Action summary
          pull-request: true # Set to true to comment on PR if available
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ctrf-reports/ctrf-report.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: custom-artifact-name
          path: ctrf-reports/ctrf-report-no-fails.json
