name: Testing

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format:check
      - name: Test
        run: npm run test
      - name: Publish Test Report
        uses: ./
        with:
          report-path: './ctrf/*.json'
          summary-report: true
          previous-results-report: true
          flaky-rate-report: true
          fail-rate-report: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
      - name: Print GitHub Context
        env:
          CONTEXT: ${{ toJson(github) }}
        run: echo "$CONTEXT" | jq .
        if: always()


      - name: Publish PR Comment
        uses: ./
        with:
          report-path: './ctrf/*.json'
          pull-request-report: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ctrf/ctrf-report.json